# Generated by Django 4.2.7 on 2025-09-17 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitrequest',
            name='location_city',
            field=models.CharField(choices=[('noida', 'Noida'), ('gurgaon', 'Gurgaon'), ('delhi', 'Delhi'), ('faridabad', 'Faridabad'), ('ghaziabad', 'Ghaziabad'), ('other', 'Other')], default='noida', max_length=50),
        ),
        migrations.AddField(
            model_name='sitevisitrequest',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitevisitrequest',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
