# Generated by Django 4.2.7 on 2025-09-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_sitevisitrequest_location_city_and_more'),
    ]

    operations = [
    ]
