# Generated by Django 4.2.7 on 2025-09-18 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0004_auto_20250917_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('address', models.TextField(blank=True)),
                ('response_type', models.CharField(choices=[('location', 'Location'), ('text', 'Text')], default='location', max_length=20)),
                ('message_content', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site_visit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_responses', to='crm_app.sitevisitrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
